/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/table.glb 
*/

import React from "react";
import * as THREE from "three";
import { Suspense, useEffect, useLayoutEffect } from "react";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import {
  ScrollControls,
  Sky,
  useScroll,
  useGLTF,
  useAnimations,
} from "@react-three/drei";

export default function Room(props) {
  const { nodes, materials } = useGLTF("./models/table.glb");
  const CAMERA_INITIAL_POSITION = [0, 5.7533, 14.4358];
  const CAMERA_FINAL_POSITION = [0.9772, 5.523, 28.9418];
  const CAMERA_INITIAL_ROTATION = [0.005, 0, 0];
  const CAMERA_FINAL_ROTATION = [0, 2.9442 - 2 * Math.PI, 0];

  const scroll = useScroll();
  useFrame((state, delta) => {
    const offset = scroll.offset;

    state.camera.position.set(
      CAMERA_INITIAL_POSITION[0] +
        (CAMERA_FINAL_POSITION[0] - CAMERA_INITIAL_POSITION[0]) * offset,
      CAMERA_INITIAL_POSITION[1] +
        (CAMERA_FINAL_POSITION[1] - CAMERA_INITIAL_POSITION[1]) * offset,
      CAMERA_INITIAL_POSITION[2] +
        (CAMERA_FINAL_POSITION[2] - CAMERA_INITIAL_POSITION[2]) * offset
    );
    state.camera.rotation.set(
      CAMERA_INITIAL_ROTATION[0] +
        (CAMERA_FINAL_ROTATION[0] - CAMERA_INITIAL_ROTATION[0]) * offset,
      CAMERA_INITIAL_ROTATION[1] +
        (CAMERA_FINAL_ROTATION[1] - CAMERA_INITIAL_ROTATION[1]) * offset,
      CAMERA_INITIAL_ROTATION[2] +
        (CAMERA_FINAL_ROTATION[2] - CAMERA_INITIAL_ROTATION[2]) * offset
    );
  });
  return (
    <group {...props} dispose={null}>
      <group
        position={[-2.061, 3.809, 35.169]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.18}
      >
        <mesh
          geometry={nodes.Cube021.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Cube021_2.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        geometry={nodes.Hand.geometry}
        material={materials["Skin.002"]}
        position={[-2.082, 3.702, 27.181]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Hand_sleeve.geometry}
        material={materials["Sleeve.001"]}
        position={[-2.082, 3.702, 27.181]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Head.geometry}
        material={materials["Skin.003"]}
        position={[-0.033, 4.323, 6.102]}
        rotation={[-3.089, 0, Math.PI]}
      />
      <group
        position={[0.485, 5.41, 6.731]}
        rotation={[-1.446, -0.001, 3.056]}
        scale={1.446}
      >
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={materials.Eyeyball}
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={materials.Pupil}
        />
      </group>
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.Eyebrow}
        position={[0.572, 5.953, 7.037]}
        rotation={[1.623, 0, -3.142]}
        scale={[1.652, 0.78, 0.557]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.Hair}
        position={[-0.033, 5.739, 5.732]}
        rotation={[2.904, 0, -3.142]}
        scale={[4.911, 4.19, 4.808]}
      />
      <mesh
        geometry={nodes.Body.geometry}
        material={materials.Shirt}
        position={[0.04, 2.451, 5.167]}
        rotation={[-3.089, 0, Math.PI]}
        scale={1.508}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["Sleeve.002"]}
        position={[0.109, 3.713, 5.708]}
        rotation={[1.623, 0, -3.142]}
        scale={[3.735, 0.858, 0.627]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Material.019"]}
        position={[-0.402, 6.53, 6.409]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials["Material.019"]}
        position={[-0.075, 6.561, 6.471]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["Material.019"]}
        position={[0.216, 6.554, 6.592]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials["Material.019"]}
        position={[0.59, 6.525, 6.592]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials["Material.019"]}
        position={[0.973, 6.605, 6.592]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials["Material.019"]}
        position={[-0.373, 6.516, 6.358]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials["Material.019"]}
        position={[-1.148, 5.778, 6.32]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.341}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials["Material.019"]}
        position={[-1.183, 5.433, 6.32]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.341}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials["Material.019"]}
        position={[0.966, 6.025, 6.494]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.287}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials["Material.019"]}
        position={[1.079, 5.711, 6.494]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.287}
      />
      <mesh
        geometry={nodes.Back.geometry}
        material={materials["Material.015"]}
        position={[0, 6.027, 0]}
        rotation={[Math.PI / 2, 0, -3.142]}
        scale={[-53.681, -53.681, -24.108]}
      />
      <mesh
        geometry={nodes.Left_wall.geometry}
        material={materials["Material.009"]}
        position={[13.419, 6.027, 18.77]}
        rotation={[Math.PI / 2, 0, 1.571]}
        scale={[-75.076, -53.681, -24.108]}
      />
      <mesh
        geometry={nodes.Window.geometry}
        material={materials.Wall}
        position={[-0.002, 6.027, 37.538]}
        rotation={[Math.PI / 2, 0, -3.142]}
        scale={[-53.681, -53.681, -24.108]}
      />
      <mesh
        geometry={nodes.Right_wall.geometry}
        material={materials["Material.016"]}
        position={[-13.421, 6.027, 18.768]}
        rotation={[Math.PI / 2, 0, 1.571]}
        scale={[-75.076, -53.681, -24.108]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.Material}
        position={[13.296, 6.027, 37.415]}
        scale={[-0.277, -23.952, -0.551]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.001"]}
        position={[-13.3, 6.027, 37.414]}
        scale={[-0.277, -23.952, -0.551]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.006"]}
        position={[13.298, 6.027, 0.089]}
        scale={[-0.277, -23.952, -0.551]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.007"]}
        position={[-13.298, 6.027, 0.088]}
        scale={[-0.277, -23.952, -0.551]}
      />
      <mesh
        geometry={nodes.Floor.geometry}
        material={materials["Material.018"]}
        position={[0, 0.1, 18.769]}
        rotation={[0, 0, -Math.PI]}
        scale={[-53.678, -1, -75.076]}
      />
      <mesh
        geometry={nodes.Roof.geometry}
        material={materials["Material.017"]}
        position={[0, 12.054, 18.769]}
        rotation={[0, 0, -Math.PI]}
        scale={[-53.678, -1, -75.076]}
      />
      <group
        position={[0.543, 6.017, 37.038]}
        rotation={[Math.PI / 2, 0, -3.142]}
        scale={0.218}
      >
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials["Glossy material"]}
        />
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={materials.Screen}
        />
      </group>
      <mesh
        geometry={nodes.Table.geometry}
        material={materials["Material.008"]}
        position={[-0.002, 3.542, 35.259]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.336, 1.35, 1.35]}
      />
    </group>
  );
}

useGLTF.preload("./models/table.glb");
