/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/table.glb 
*/

import React, { useState } from "react";
import { Color } from "three";
import { useFrame } from "@react-three/fiber";
import { useScroll, useGLTF, Html } from "@react-three/drei";
import "./styles.css";
import Project from "./Project";
import Stars from "./Stars";

const roomBloomColor = new Color("#ffffff");
const keyboardBloomColor = new Color("ffffff");
const monitorBloomColor = new Color("ffffff");
const mousepadBloomColor = new Color("ffffff");
const tableBloomColor = new Color("ffffff");

roomBloomColor.multiplyScalar(1.5);
keyboardBloomColor.multiplyScalar(1.5);
monitorBloomColor.multiplyScalar(1.5);
mousepadBloomColor.multiplyScalar(1.5);
tableBloomColor.multiplyScalar(1.5);

const projList = {
  micrograd_plus: [
    "https://github.com/siddiskid/micrograd_plus",
    "Inspired by Andrej Karpathy's micrograd, micrograd_plus is an autograd engine over scalar-valued Directed Acyclic Graphs. It extends micrograd by implementing additional activation functions, like sigmoid and relu, in addition to the included tanh along with a draw function that draws a DAG with all neurons and their gradients. micrograd_plus can be used to make neural networks for binary classification tasks",
    ["Python", "PyTorch", "Tensorflow"],
  ],
  worklearn_scraper: [
    "https://github.com/siddiskid/worklearn_scraper",
    "A web scraping application used to get job listing data from careers online on an excel sheet. Built to save time on reading job requirements and spend that on actually applying to jobs",
    ["Python", "Excel", "Pandas"],
  ],
  "Ryu's Conquest": [
    "https://github.com/siddiskid/Snakes-and-Hackers-II",
    "Once upon a time, a village is invaded by an army of malevolent robots. Upon leaving, they took away the most valuable things in the world — games. While the inhabitants of the village were filled with sadness, a brave warrior named Ryu has decided to step up and go on a quest to bring back the games. To do that, he needs to beat the robots in four classic games on planet Xamos, Opus, Icrozar, and Duex. Let’s see if he can beat the robots!",
    ["JS", "React"],
  ],
  "Budget Buddy": [
    "https://github.com/siddiskid/budget_buddy",
    "Budget Buddy is a dynamic budget tracking app designed to make managing your finances a breeze. With insights about your spending habits, monthly and weekly statistics, and ability to set realistic budget limits, Budget Buddy helps you develop healthy financial habits and makes adulting a little bit easier",
    ["Java"],
  ],
  "Wellness 360": [
    "https://github.com/siddiskid/Wellness360",
    "Wellness 360 is a website which shows users the nearest health and lifestyle locations and lets them book appointments with any of these places. It also has a chatbot which asks the user what symptoms they are facing and tells them the disease they are most likely affected by. Additionally, Wellness 360 Enterprise is a website for businesses, where they can register themselves with us and get updates on appointments booked with them.",
    ["JS", "React"],
  ],
};

export default function Room(props) {
  const { nodes, materials } = useGLTF("./models/table.glb");
  const CAMERA_INITIAL_POSITION = [0, 5.7533, 14.4358];
  const CAMERA_FINAL_POSITION = [0.9772, 5.523, 28.9418];
  const CAMERA_INITIAL_ROTATION = [0.005, 0, 0];
  const CAMERA_FINAL_ROTATION = [0, 2.9442 - 2 * Math.PI, 0];

  const [currProj, updateCurrProj] = useState(
    "Hover on a project to preview, click on it to check it out"
  );
  const [currProjDesc, updateCurrProjDesc] = useState("NONE");
  const [currProjStack, updateCurrProjStack] = useState(["NONE"]);

  const scroll = useScroll();
  useFrame((state, delta) => {
    const offset = scroll.offset;

    state.camera.position.set(
      CAMERA_INITIAL_POSITION[0] +
        (CAMERA_FINAL_POSITION[0] - CAMERA_INITIAL_POSITION[0]) * offset,
      CAMERA_INITIAL_POSITION[1] +
        (CAMERA_FINAL_POSITION[1] - CAMERA_INITIAL_POSITION[1]) * offset,
      CAMERA_INITIAL_POSITION[2] +
        (CAMERA_FINAL_POSITION[2] - CAMERA_INITIAL_POSITION[2]) * offset
    );
    state.camera.rotation.set(
      CAMERA_INITIAL_ROTATION[0] +
        (CAMERA_FINAL_ROTATION[0] - CAMERA_INITIAL_ROTATION[0]) * offset,
      CAMERA_INITIAL_ROTATION[1] +
        (CAMERA_FINAL_ROTATION[1] - CAMERA_INITIAL_ROTATION[1]) * offset,
      CAMERA_INITIAL_ROTATION[2] +
        (CAMERA_FINAL_ROTATION[2] - CAMERA_INITIAL_ROTATION[2]) * offset
    );
  });
  return (
    <group {...props} dispose={null}>
      <Html
        position={[0, 0.25, 0]}
        transform
        portal={{ current: scroll.fixed }}
      >
        <div className="scrollToNavigate">Scroll to nagivate</div>
      </Html>

      <group
        position={[-2.061, 3.809, 35.169]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.18}
      >
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Cube021_2.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Cube021_3.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        geometry={nodes.Hand.geometry}
        material={materials["Skin.002"]}
        position={[-2.082, 3.702, 27.181]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Hand_sleeve.geometry}
        material={materials["Sleeve.001"]}
        position={[-2.082, 3.702, 27.181]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Head.geometry}
        material={materials["Skin.003"]}
        position={[-0.033, 4.323, 6.102]}
        rotation={[-3.089, 0, Math.PI]}
      />
      <group
        position={[0.485, 5.41, 6.731]}
        rotation={[-1.446, -0.001, 3.056]}
        scale={1.446}
      >
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={materials.Eyeyball}
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={materials.Pupil}
        />
      </group>
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.Eyebrow}
        position={[0.572, 5.953, 7.037]}
        rotation={[1.623, 0, -3.142]}
        scale={[1.652, 0.78, 0.557]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.Hair}
        position={[-0.033, 5.739, 5.732]}
        rotation={[2.904, 0, -3.142]}
        scale={[4.911, 4.19, 4.808]}
      />
      <mesh
        geometry={nodes.Body.geometry}
        material={materials.Shirt}
        position={[0.04, 2.451, 5.167]}
        rotation={[-3.089, 0, Math.PI]}
        scale={1.508}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["Sleeve.002"]}
        position={[0.109, 3.713, 5.708]}
        rotation={[1.623, 0, -3.142]}
        scale={[3.735, 0.858, 0.627]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Material.019"]}
        position={[-0.402, 6.53, 6.409]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials["Material.019"]}
        position={[-0.075, 6.561, 6.471]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["Material.019"]}
        position={[0.216, 6.554, 6.592]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials["Material.019"]}
        position={[0.59, 6.525, 6.592]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials["Material.019"]}
        position={[0.973, 6.605, 6.592]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials["Material.019"]}
        position={[-0.373, 6.516, 6.358]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials["Material.019"]}
        position={[-1.148, 5.778, 6.32]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.341}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials["Material.019"]}
        position={[-1.183, 5.433, 6.32]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.341}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials["Material.019"]}
        position={[0.966, 6.025, 6.494]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.287}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials["Material.019"]}
        position={[1.079, 5.711, 6.494]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.287}
      />
      <group
        position={[0.543, 6.017, 37.038]}
        rotation={[Math.PI / 2, 0, -3.142]}
        scale={0.218}
      >
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials["Glossy material"]}
        />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials.Screen}>
          <meshStandardMaterial />
          <Html
            position={[-0.05, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            transform
            portal={{ current: scroll.fixed }}
          >
            <Project
              projName={currProj}
              projDesc={currProjDesc}
              projStack={currProjStack}
            />
          </Html>
        </mesh>
      </group>
      <mesh
        geometry={nodes.Table.geometry}
        material={materials["Material.008"]}
        position={[-0.002, 3.542, 35.259]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.336, 1.35, 1.35]}
      />
      <mesh
        position={[-4.15, 6.017, 35.726]}
        rotation={[Math.PI / 2, 0, 0.466]}
      />
      <meshStandardMaterial />
      <Html
        position={[-4.15, 6.017, 35.726]}
        rotation={[0, 2.9, 0]}
        scale={0.25}
        transform
        portal={{ current: scroll.fixed }}
      >
        <div className="wrapper">
          {Object.entries(projList).map(([key, value]) => (
            <div
              key={value[0]}
              className="text"
              onMouseEnter={() => {
                updateCurrProj(key);
                updateCurrProjDesc(value[1]);
                updateCurrProjStack(value[2]);
                console.log(currProj);
              }}
              onMouseLeave={() => {
                updateCurrProj(
                  "Hover on a project to preview, click on it to check it out"
                );
                updateCurrProjDesc("NONE");
                updateCurrProjStack("NONE");
              }}
            >
              <a href={value[0]}>{key}</a>
            </div>
          ))}
        </div>
      </Html>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        position={[-0.061, 3.787, 34.606]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.001"]}
        position={[-0.319, 3.787, 34.573]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        position={[0.197, 3.787, 34.639]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["Material.001"]}
        position={[0.456, 3.787, 34.673]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials["Material.001"]}
        position={[2.164, 3.787, 34.892]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials["Material.001"]}
        position={[2.421, 3.787, 34.926]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["Material.001"]}
        position={[2.679, 3.787, 34.959]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["Material.001"]}
        position={[-0.176, 3.786, 34.818]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Material.001"]}
        position={[2.561, 3.786, 35.171]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials["Material.001"]}
        position={[-0.283, 3.786, 35.031]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials["Material.001"]}
        position={[-0.383, 3.786, 35.245]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["Material.001"]}
        position={[-0.367, 3.787, 35.473]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Material.001"]}
        position={[2.564, 3.786, 35.397]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials["Material.001"]}
        position={[2.572, 3.786, 35.626]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.001"]}
        position={[1.309, 3.787, 34.782]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.001"]}
        position={[2.228, 3.786, 35.128]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials["Material.001"]}
        position={[2.263, 3.786, 35.359]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials["Material.001"]}
        position={[2.31, 3.786, 35.592]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials["Material.001"]}
        position={[2.583, 3.732, 35.865]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[0.106, 0.105, 0.106]}
      />
      <mesh
        geometry={nodes.base.geometry}
        material={materials["Material.004"]}
        position={[1.121, 3.52, 35.212]}
        rotation={[-Math.PI, 0.128, -Math.PI]}
        scale={[1.719, 0.133, 0.636]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Mousepad}
        position={[0.162, 3.551, 35.235]}
        scale={[13.094, 2.348, 4.468]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[1.167, 3.684, 34.884]}
        rotation={[Math.PI, 0.128, Math.PI / 2]}
        scale={[0.01, 6.499, 0.013]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[1.147, 3.684, 35.105]}
        rotation={[Math.PI, 0.128, Math.PI / 2]}
        scale={[0.01, 6.499, 0.013]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
        position={[1.108, 3.684, 35.327]}
        rotation={[Math.PI, 0.128, Math.PI / 2]}
        scale={[0.01, 6.499, 0.013]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[1.08, 3.684, 35.551]}
        rotation={[Math.PI, 0.128, Math.PI / 2]}
        scale={[0.01, 6.499, 0.013]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={nodes.Cylinder015.material}
        position={[2.549, 3.684, 34.947]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={nodes.Cylinder016.material}
        position={[2.289, 3.684, 34.913]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={nodes.Cylinder017.material}
        position={[2.031, 3.684, 34.879]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={nodes.Cylinder018.material}
        position={[0.582, 3.684, 34.694]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={nodes.Cylinder019.material}
        position={[0.325, 3.684, 34.662]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={nodes.Cylinder020.material}
        position={[0.068, 3.684, 34.625]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={nodes.Cylinder021.material}
        position={[-0.191, 3.684, 34.59]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={nodes.Cylinder022.material}
        position={[0.126, 3.684, 34.862]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={nodes.Cylinder023.material}
        position={[-0.06, 3.684, 35.065]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={nodes.Cylinder024.material}
        position={[-0.231, 3.684, 35.265]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={nodes.Cylinder025.material}
        position={[-0.172, 3.684, 35.502]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={nodes.Cylinder026.material}
        position={[0.048, 3.684, 35.525]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={nodes.Cylinder027.material}
        position={[-0.01, 3.684, 35.297]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[0.164, 3.684, 35.094]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={nodes.Cylinder029.material}
        position={[0.384, 3.684, 35.123]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={nodes.Cylinder030.material}
        position={[0.349, 3.684, 34.892]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[0.211, 3.684, 35.327]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={nodes.Cylinder032.material}
        position={[0.267, 3.684, 35.559]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={nodes.Cylinder033.material}
        position={[0.488, 3.684, 35.587]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={nodes.Cylinder034.material}
        position={[0.432, 3.684, 35.353]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder035.geometry}
        material={nodes.Cylinder035.material}
        position={[0.605, 3.684, 35.15]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={nodes.Cylinder036.material}
        position={[0.653, 3.684, 35.383]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={nodes.Cylinder037.material}
        position={[0.707, 3.684, 35.615]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder038.geometry}
        material={nodes.Cylinder038.material}
        position={[0.874, 3.684, 35.412]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder039.geometry}
        material={nodes.Cylinder039.material}
        position={[1.094, 3.684, 35.439]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder040.geometry}
        material={nodes.Cylinder040.material}
        position={[0.929, 3.684, 35.643]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder041.geometry}
        material={nodes.Cylinder041.material}
        position={[1.148, 3.684, 35.669]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder042.geometry}
        material={nodes.Cylinder042.material}
        position={[1.372, 3.684, 35.699]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder043.geometry}
        material={nodes.Cylinder043.material}
        position={[1.314, 3.684, 35.471]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder044.geometry}
        material={nodes.Cylinder044.material}
        position={[1.536, 3.684, 35.496]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder045.geometry}
        material={nodes.Cylinder045.material}
        position={[1.591, 3.684, 35.726]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder046.geometry}
        material={nodes.Cylinder046.material}
        position={[1.756, 3.684, 35.525]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder047.geometry}
        material={nodes.Cylinder047.material}
        position={[1.812, 3.684, 35.757]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder048.geometry}
        material={nodes.Cylinder048.material}
        position={[2.032, 3.684, 35.785]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder049.geometry}
        material={nodes.Cylinder049.material}
        position={[2.252, 3.684, 35.813]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder050.geometry}
        material={nodes.Cylinder050.material}
        position={[2.473, 3.684, 35.844]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder051.geometry}
        material={nodes.Cylinder051.material}
        position={[1.977, 3.684, 35.555]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder052.geometry}
        material={nodes.Cylinder052.material}
        position={[2.198, 3.684, 35.584]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder053.geometry}
        material={nodes.Cylinder053.material}
        position={[2.42, 3.684, 35.609]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder054.geometry}
        material={nodes.Cylinder054.material}
        position={[2.374, 3.684, 35.378]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder055.geometry}
        material={nodes.Cylinder055.material}
        position={[2.151, 3.684, 35.348]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder056.geometry}
        material={nodes.Cylinder056.material}
        position={[1.929, 3.684, 35.321]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder057.geometry}
        material={nodes.Cylinder057.material}
        position={[1.71, 3.684, 35.291]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder058.geometry}
        material={nodes.Cylinder058.material}
        position={[1.488, 3.684, 35.262]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder059.geometry}
        material={nodes.Cylinder059.material}
        position={[1.268, 3.684, 35.233]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder060.geometry}
        material={nodes.Cylinder060.material}
        position={[1.047, 3.684, 35.203]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder061.geometry}
        material={nodes.Cylinder061.material}
        position={[0.826, 3.684, 35.175]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder062.geometry}
        material={nodes.Cylinder062.material}
        position={[0.565, 3.684, 34.919]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder063.geometry}
        material={nodes.Cylinder063.material}
        position={[0.79, 3.684, 34.948]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder064.geometry}
        material={nodes.Cylinder064.material}
        position={[1.013, 3.684, 34.977]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder065.geometry}
        material={nodes.Cylinder065.material}
        position={[1.234, 3.684, 35.005]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder066.geometry}
        material={nodes.Cylinder066.material}
        position={[1.454, 3.684, 35.033]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder067.geometry}
        material={nodes.Cylinder067.material}
        position={[1.674, 3.684, 35.061]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder068.geometry}
        material={nodes.Cylinder068.material}
        position={[1.896, 3.684, 35.09]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder069.geometry}
        material={nodes.Cylinder069.material}
        position={[2.117, 3.684, 35.119]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder070.geometry}
        material={nodes.Cylinder070.material}
        position={[2.34, 3.684, 35.147]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.01, 0.414, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder071.geometry}
        material={nodes.Cylinder071.material}
        position={[1.197, 3.684, 34.657]}
        rotation={[Math.PI, 0.128, Math.PI / 2]}
        scale={[0.01, 6.499, 0.013]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder072.geometry}
        material={nodes.Cylinder072.material}
        position={[1.036, 3.684, 35.765]}
        rotation={[Math.PI, 0.128, Math.PI / 2]}
        scale={[0.01, 6.499, 0.013]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder073.geometry}
        material={nodes.Cylinder073.material}
        position={[-0.507, 3.684, 35]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.012, 2.246, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder074.geometry}
        material={nodes.Cylinder074.material}
        position={[2.747, 3.684, 35.423]}
        rotation={[Math.PI / 2, 0, -3.014]}
        scale={[0.012, 2.246, 0.01]}
      >
        <meshBasicMaterial color={keyboardBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Monitor_Neon_Left.geometry}
        material={nodes.Monitor_Neon_Left.material}
        position={[4.033, 6.017, 37.029]}
        scale={[0.01, 7.87, 0.01]}
      >
        <meshBasicMaterial color={monitorBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Monitor_Neon_Top.geometry}
        material={nodes.Monitor_Neon_Top.material}
        position={[0.548, 7.985, 37.029]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 13.95, 0.01]}
      >
        <meshBasicMaterial color={monitorBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Monitor_Neon_Bottom.geometry}
        material={nodes.Monitor_Neon_Bottom.material}
        position={[0.548, 4.053, 37.029]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 13.921, 0.01]}
      >
        <meshBasicMaterial color={monitorBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Monitor_Neon_Right.geometry}
        material={nodes.Monitor_Neon_Right.material}
        position={[-2.938, 6.017, 37.029]}
        scale={[0.01, 7.87, 0.01]}
      >
        <meshBasicMaterial color={monitorBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Mousepad_neon_back.geometry}
        material={nodes.Mousepad_neon_back.material}
        position={[0.162, 3.549, 36.353]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 13.085, 0.01]}
      >
        <meshBasicMaterial color={mousepadBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Mousepad_neon_front.geometry}
        material={nodes.Mousepad_neon_front.material}
        position={[0.162, 3.549, 34.114]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 13.085, 0.01]}
      >
        <meshBasicMaterial color={mousepadBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Mousepad_neon_right.geometry}
        material={nodes.Mousepad_neon_right.material}
        position={[-3.112, 3.549, 35.235]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 4.477, 0.01]}
      >
        <meshBasicMaterial color={mousepadBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Mousepad_neon_left.geometry}
        material={nodes.Mousepad_neon_left.material}
        position={[3.435, 3.549, 35.235]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 4.477, 0.01]}
      >
        <meshBasicMaterial color={mousepadBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Table_neon_back_left.geometry}
        material={nodes.Table_neon_back_left.material}
        position={[4.332, 1.82, 36.613]}
        rotation={[0, 0, Math.PI]}
        scale={[0.01, 6.11, 0.01]}
      >
        <meshBasicMaterial color={tableBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Table_neon_back_right.geometry}
        material={nodes.Table_neon_back_right.material}
        position={[-4.332, 1.82, 36.613]}
        rotation={[0, 0, Math.PI]}
        scale={[0.01, 6.11, 0.01]}
      >
        <meshBasicMaterial color={tableBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Table_neon_front_left.geometry}
        material={nodes.Table_neon_front_left.material}
        position={[4.332, 1.82, 33.91]}
        rotation={[0, 0, Math.PI]}
        scale={[0.01, 6.11, 0.01]}
      >
        <meshBasicMaterial color={tableBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Table_neon_front_right.geometry}
        material={nodes.Table_neon_front_right.material}
        position={[-4.335, 1.82, 33.91]}
        rotation={[0, 0, Math.PI]}
        scale={[0.01, 6.11, 0.01]}
      >
        <meshBasicMaterial color={tableBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Table_neon_front_top.geometry}
        material={nodes.Table_neon_front_top.material}
        position={[0, 3.542, 33.91]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 14.872, 0.01]}
      >
        <meshBasicMaterial color={tableBloomColor} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Table_neon_back_top.geometry}
        material={nodes.Table_neon_back_top.material}
        position={[0, 3.542, 36.613]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 14.872, 0.01]}
      >
        <meshBasicMaterial color={tableBloomColor} toneMapped={false} />
      </mesh>
      <Stars />
    </group>
  );
}

useGLTF.preload("./models/table.glb");
