/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/table.glb 
*/

import React from "react";
import { Color } from "three";
import { Suspense, useEffect, useLayoutEffect } from "react";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import {
  ScrollControls,
  Sky,
  useScroll,
  useGLTF,
  useAnimations,
  Text,
  useFont,
} from "@react-three/drei";

const bloomColor = new Color("#fff");
bloomColor.multiplyScalar(1.5);

export default function Writing(props) {
  return (
    <group position-x={0} position-y={6.9033} position-z={9.9358}>
      <Text font="fonts/Roboto/Roboto-Thin.ttf" scale={0.6}>
        Hey, I'm Siddarth
        <meshBasicMaterial color={bloomColor} toneMapped={false} />
      </Text>
    </group>
  );
}

useFont.preload("fonts/Roboto/Roboto-Thin.ttf");
